modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="dawnautotranslator"
version="1.5.4"
displayName="Dawn Auto Translator v1.5 overlay fix"
description='''Prototype client-side auto translator for untranslated English GUI/chat strings in DawnCraft/Forge 1.18.2.'''
